<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>添加用户</title>
    <style>
        .keleyitable {
            width: 800px;
        }

        .keleyitable table, td, th
        {
            border: 1px solid dodgerblue;margin-top:10px;
            border-collapse: collapse;
        }
        .klytd
        {
            width:100px;
            text-align:center;
        }
        .hvttd
        {
            width:500px;
            text-align:center;
        }
    </style>

</head>
<body>
<div style="margin:0px auto;" class="keleyitable">
    <span style="margin-left:42%;">
        <font size="+2">编辑用户</font>
        <a href="../../index">返回列表</a>
    </span>
    <form name="form1" method="post" action="../../update/">
        <table style="margin-left:30%;">
            <tr>
                <td width="100px;">用户名：</td>
                <td width="200px;"><input  type="text" name="name" style="width:200px;" value="<?php echo $userInfo['name'];?>"></td>
            </tr>
            <tr>
                <td>性别：</td>
                <td>
                    <select name="sex">
                        <option value="1" <?php if($userInfo["sex"] == 1){ echo "selected";}?>>男</option>
                        <option value="2" <?php if($userInfo["sex"] == 2){ echo "selected";}?>>女</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>邮箱：</td>
                <td><input type="text" name="email" style="width:200px;" value="<?php echo $userInfo['email'];?>"></td>
            </tr>

            <tr>
                <td colspan="2" align="center">
                    <input type="hidden" name="id" value="<?php echo $userInfo['id'];?>">
                    <input type="reset" name="reset" value="重置">
                    <input type="submit" name="submit" value="提交">
                </td>
            </tr>

        </table>
    </form>

</div>
</body>
</html>