<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>用户信息列表</title>
    <style>
        .keleyitable {
            width: 800px;
        }

        .keleyitable table, td, th
        {
            border: 1px solid dodgerblue;margin-top:10px;
            border-collapse: collapse;
        }
        .klytd
        {
            width:100px;
            text-align:center;
        }
        .hvttd
        {
            width:500px;
            text-align:center;
        }
    </style>

</head>
<body>
<div style="margin:0px auto;" class="keleyitable">
    <span style="margin-left:30%;">
        <font size="+3">用户信息列表</font>
        <a href="./create">新建</a>
    </span>
    <br><br>
    <form name="form1" action="./search" method="post">
    <span style="margin-left:55%;">
        用户名:<input type="text" name="name" value="">
        &nbsp;&nbsp;
        性别：<select name="sex">
                    <option value="">...</option>
                    <option value="1">男</option>
                    <option value="2">女</option>
                </select>
        <input type="submit" name="submit" value="搜索">
    </span>
    </form>
    <table>
        <tr>
            <td class="klytd">ID</td>
            <td class="hvttd">姓名</td>
            <td class="hvttd">性别</td>
            <td class="hvttd">邮箱</td>
            <td class="hvttd">操作</td>
        </tr>
        <?php foreach($list as $key => $val){
            ?>
            <tr>
                <td class="klytd"><?php echo $val["id"];?></td>
                <td class="klytd"><?php echo $val["name"];?></td>
                <td class="klytd"><?php echo getsex($val["sex"])?></td>
                <td class="klytd"><?php echo $val["email"]?></td>
                <td class="klytd">
                    <a href="./edit/id/<?php echo $val["id"];?>">编辑</a>&nbsp;&nbsp;
                    <a href="./delete/id/<?php echo $val["id"];?>" onclick="if(confirm('确定删除?')==false)return false;">删除</a>
                </td>
            </tr>
        <?php
        }
        ?>

    </table>

    <?php
        function getsex($sex_id)
        {
            $sex = "";
            if($sex_id == 1){
                $sex = "男";
            }else if($sex_id == 2){
                $sex = "女";
            }
            return $sex;
        }
    ?>

</div>
</body>
</html>